version: "3.9"
services:
  fastapi-data-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-data-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app-docker
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - PYTHONPATH=.
    env_file:
      - .env
    networks:
      - fastapi-network
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks: 
      - fastapi-network
  celery-worker:
    build: 
      context: .
      dockerfile: Dockerfile.celery
    volumes:
      - .:/app-docker
    depends_on:
      - redis
    environment:
      - PYTHONPATH=.
    env_file:
      - .env
    networks:
      - fastapi-network
networks:
  fastapi-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
    
  